[package]
name = "brml-bridge"
version = "0.1.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"

[dependencies]
brml-assets = { path = "../assets", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
eos-keys = { path = "/Users/edwin/liebi/polkadot/rust-eos/keys", optional = true }
eos-primitives = { path = "/Users/edwin/liebi/polkadot/rust-eos/primitives", optional = true }
eos-rpc = { path = "/Users/edwin/liebi/polkadot/rust-eos/rpc", optional = true }
inherents = { package = "substrate-inherents", git = "https://github.com/paritytech/substrate", default-features = false }
node-primitives = { path = "../../node/primitives", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate", default-features = false }
sr-io = { git = "https://github.com/paritytech/substrate", default-features = false }
sr-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }
srml-support = { git = "https://github.com/paritytech/substrate", default-features = false }
substrate-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/paritytech/substrate", default-features = false }

[dev-dependencies]
sr-primitives = { git = "https://github.com/paritytech/substrate" }
substrate-offchain = { git = "https://github.com/paritytech/substrate" }

[features]
default = ["std"]
std = [
	"brml-assets/std",
	"codec/std",
	"eos-keys/std",
	"eos-primitives/std",
	"eos-rpc/std",
	"inherents/std",
	"node-primitives/std",
	"rstd/std",
	"sr-io/std",
	"sr-primitives/std",
	"srml-support/std",
	"substrate-primitives/std",
	"system/std",
]
