[package]
name = "node-inspect"
version = "0.3.3"
authors = ["Jamie <djptux@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1" }
derive_more = "0.99"
log = "0.4.8"
sc-cli = "0.8.0-rc4"
sc-client-api = "2.0.0-rc4"
sc-service = { version = "0.8.0-rc4", default-features = false }
sp-blockchain = "2.0.0-rc4"
sp-core = "2.0.0-rc4"
sp-runtime = "2.0.0-rc4"
structopt = "0.3.8"
