[package]
name = "node-inspect"
version = "0.2.2"
authors = ["Jamie <djptux@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.2.0" }
derive_more = "0.99"
log = "0.4.8"
sc-cli = { version = "0.8.0-alpha.4", git = "https://github.com/paritytech/substrate" }
sc-client-api = { version = "2.0.0-alpha.4", git = "https://github.com/paritytech/substrate" }
sc-service = { version = "0.8.0-alpha.4", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-blockchain = { version = "2.0.0-alpha.4", git = "https://github.com/paritytech/substrate" }
sp-core = { version = "2.0.0-alpha.4", git = "https://github.com/paritytech/substrate" }
sp-runtime = { version = "2.0.0-alpha.4", git = "https://github.com/paritytech/substrate" }
structopt = "0.3.8"
