[package]
name = "node-inspect"
version = "0.8.0"
authors = ["Jamie <djptux@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
derive_more = "0.99"
log = "0.4.8"
sc-cli = "0.9.0"
sc-client-api = "3.0.0"
sc-service = { version = "0.9.0", default-features = false }
sp-blockchain = "3.0.0"
sp-core = "3.0.0"
sp-runtime = "3.0.0"
structopt = "0.3.8"
