[package]
name = "subkey"
version = "0.7.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "subkey"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-system = "3.0.0"
futures = "0.1.29"
hex = "0.4.2"
jsonrpc-core-client = { version = "15.1.0", features = ["http"] }
sc-cli = "0.9.0"
sc-rpc = "3.0.0"
sp-core = "3.0.0"
structopt = "0.3.14"
tokio = "0.1.22"

[features]
bench = []
