[package]
name = "subkey"
version = "0.2.2"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.29"
sp-core = { version = "2.0.0-alpha.5", git = "https://github.com/paritytech/substrate" }
node-runtime = { version = "*", path = "../../node/runtime" }
node-primitives = { version = "*", path = "../../node/primitives" }
sp-runtime = { version = "2.0.0-alpha.5", git = "https://github.com/paritytech/substrate" }
rand = "0.7.2"
clap = "2.33.0"
tiny-bip39 = "0.7"
substrate-bip39 = "0.4.1"
hex = "0.4.0"
hex-literal = "0.2.1"
codec = { package = "parity-scale-codec", version = "1.3.0" }
frame-system = { version = "2.0.0-alpha.5", git = "https://github.com/paritytech/substrate" }
pallet-balances = { version = "2.0.0-alpha.5", git = "https://github.com/paritytech/substrate" }
pallet-transaction-payment = { version = "2.0.0-alpha.5", git = "https://github.com/paritytech/substrate" }
rpassword = "4.0.1"
itertools = "0.8.2"
derive_more = { version = "0.99.2" }
sc-rpc = { version = "2.0.0-alpha.5", git = "https://github.com/paritytech/substrate" }
jsonrpc-core-client = { version = "14.0.3", features = ["http"] }
hyper = "0.12.35"
libp2p = "0.18.0"
serde_json = "1.0"

[features]
bench = []
