[package]
name = "subkey"
version = "0.4.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.29"
sp-core = "2.0.0-rc4"
node-runtime = { version = "*", path = "../../node/runtime" }
node-primitives = { version = "*", path = "../../node/primitives" }
sp-runtime = "2.0.0-rc4"
rand = "0.7.2"
clap = "2.33.0"
tiny-bip39 = "0.7"
substrate-bip39 = "0.4.1"
hex = "0.4.0"
hex-literal = "0.2.1"
codec = { package = "parity-scale-codec", version = "1.3.1" }
frame-system = "2.0.0-rc4"
pallet-balances = "2.0.0-rc4"
pallet-transaction-payment = "2.0.0-rc4"
pallet-grandpa = "2.0.0-rc4"
rpassword = "4.0.1"
itertools = "0.8.2"
derive_more = { version = "0.99.2" }
sc-rpc = "2.0.0-rc4"
jsonrpc-core-client = { version = "14.2.0", features = ["http"] }
hyper = "0.12.35"
libp2p = { version = "0.19.1", default-features = false }
serde_json = "1.0"

[features]
bench = []
