[package]
name = "brml-convert-rpc-runtime-api"
version = "0.4.0"
authors = ["Jamie Deng <djptux@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-api = { version = "2.0.0-rc6", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
]
