# Request an environment that provides sudo (that goes with larger containers)
# and a minimal language environment.
sudo: true
dist: bionic
language: rust
rust:
  - stable

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1

before_script:
  - travis_wait sudo apt-get update -qq
  - travis_wait sudo apt install -y cmake pkg-config libssl-dev git gcc build-essential clang libclang-dev
  - travis_wait rustup update nightly
  - travis_wait rustup target add wasm32-unknown-unknown --toolchain nightly
  - rustup default stable

script:
  - travis_wait 60 cargo build

after_script:
  # Check how much free disk space left after the build
  - travis_wait df -h
