# Request an environment that provides sudo (that goes with larger containers)
# and a minimal language environment.
sudo: true
dist: xenial
language: rust
rust:
  - stable

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1

before_script:
  # Check how much space we've got on this machine.
  - df -h
  - sudo apt-get update -qq
  - sudo apt install -y cmake pkg-config libssl-dev git gcc build-essential clang libclang-dev
  - rustup update nightly
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - rustup default stable

script:
  - cargo build

after_script:
  # Check how much free disk space left after the build
  - df -h
