# Basic
hard_tabs = true
use_small_heuristics = "Max"
# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
# Consistency
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
# Misc
comment_width = 100
chain_width = 80
wrap_comments = true
match_arm_leading_pipes = "Preserve"
match_arm_blocks = false
match_block_trailing_comma = true
use_field_init_shorthand = true
binop_separator = "Back"
license_template_path = "HEADER-GPL3"
ignore = ["pallets/merkle-distributor"]