[package]
name = "node-testing"
version = "0.1.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"

[dependencies]
pallet-balances = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
sc-client = { version = "0.8", git = "https://github.com/paritytech/substrate" }
codec = { package = "parity-scale-codec", version = "1.0.0" }
pallet-contracts = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
pallet-grandpa = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
pallet-indices = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
sp-keyring = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
node-executor = { path = "../executor" }
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }
sp-core = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
sp-io = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
frame-support = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
pallet-session = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
pallet-society = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
sp-runtime = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
pallet-staking = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
sc-executor = { version = "0.8", git = "https://github.com/paritytech/substrate" }
frame-system = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
substrate-test-client = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
pallet-timestamp = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
pallet-transaction-payment = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
pallet-treasury = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
wabt = "0.9.2"

eos-chain = { git = "https://github.com/bifrost-codes/rust-eos", branch = "use-rust-secp256k1" }