[package]
name = "bifrost-bid"
version = "0.8.0"
authors = ["Herry Ho <herry.heyi@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
node-primitives = { path = "../../node/primitives", default-features = false }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
serde = { version = "1.0.106", optional = true }
sp-runtime = { version = "3.0.0", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
orml-traits = { version = "0.4.1-dev", default-features = false }
orml-currencies = { version = "0.4.1-dev", default-features = false }
orml-tokens = { version = "0.4.1-dev", default-features = false}

[dev-dependencies]
balances = { package = "pallet-balances", version = "3.0.0", default-features = false }
sp-core = { version = "3.0.0" }
sp-io = { version = "3.0.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"node-primitives/std",
	"frame-support/std",
	"frame-system/std",
	"serde/std",
	"sp-runtime/std",
	"num-traits/std",
	"orml-traits/std",
	"orml-currencies/std",
	"orml-tokens/std"
]
