[package]
name = "node-transaction-factory"
version = "0.1.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"

[dependencies]
sp-block-builder = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
sc-cli = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
sc-client-api = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
sc-client = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
codec = { package = "parity-scale-codec", version = "1.0.0", features = ["derive"] }
sp-consensus = { version = "0.8", git = "https://github.com/paritytech/substrate" }
log = "0.4.8"
sp-core = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
sp-api = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
sp-runtime = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
sc-service = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
sp-blockchain = { version = "2.0.0", git = "https://github.com/paritytech/substrate" }
