[package]
name = "bifrost-bridge-eos"
version = "0.7.0"
authors = ["Liebi Technologies <bifrost@liebi.com>"]
edition = "2021"

[dependencies]
bs58 = { version = "0.4.0", default-features = false, features = ["alloc"] }
codec = { package = "parity-scale-codec", version = "2.3.0", default-features = false, features = ["derive"] }
eos-chain = { git = "https://github.com/bifrost-finance/rust-eos", default-features = false }
eos-keys = { git = "https://github.com/bifrost-finance/rust-eos", default-features = false }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
hex = { version = "0.4.2", default-features = false }
lazy_static = { version = "1.4", features = ["spin_no_std"] }
node-primitives = { path = "../../node/primitives", default-features = false }
pallet-authorship = { version = "3.0.0", default-features = false }
sp-application-crypto = { version = "3.0.0", default-features = false }
sp-core = { version = "3.0.0", default-features = false }
sp-io = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
serde = { version = "1.0.124", optional = true }
serde_json = { version = "1.0.60", default-features = false, features = ["alloc"] }
lite-json = { version = "0.1.0", git = "https://github.com/xlc/lite-json", default-features = false, features = ["float"]}
log = { version = "0.4.14", default-features = false }
orml-traits = { version = "0.4.1-dev", default-features = false }
orml-currencies = { version = "0.4.1-dev", default-features = false }
orml-tokens = { version = "0.4.1-dev", default-features = false}
minter-reward = { package = "bifrost-minter-reward", path = "../minter-reward" }

[dev-dependencies]
assets = { package = "bifrost-assets", path = "../assets" }
vtoken-mint = { package = "bifrost-vtoken-mint", path = "../vtoken-mint" }

substrate-offchain = { version = "3.0.0", package = "sp-offchain" }
pallet-balances = { version = "3.0.0" }


[features]
default = ["std"]
std = [
	"codec/std",
	"eos-chain/std",
	"eos-keys/std",
	"frame-support/std",
	"frame-system/std",
	"hex/std",
	"log/std",
	"node-primitives/std",
	"minter-reward/std",
	"pallet-authorship/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"serde",
	"serde_json/std",
	"orml-traits/std",
	"orml-currencies/std",
	"orml-tokens/std"
]
