[package]
authors = ["Parallel Team", "Liebi Technologies <bifrost@liebi.com>"]
edition = "2021"
name = 'lend-market-rpc'
version = "0.8.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
	"derive",
] }
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] }
node-primitives = { path = "../../../node/primitives", default-features = false }
serde = { version = "1.0.160", features = ["derive"] }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", features = [
	'std',
] }
sp-blockchain = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", features = [
	'std',
] }
sp-rpc = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", features = [
	'std',
] }

lend-market-rpc-runtime-api = { path = 'runtime-api', default-features = false }

[lib]
doctest = false
