[package]
name = "brml-assets-rpc"
version = "0.3.2"
authors = ["Jamie Deng <djptux@gmail.com>"]
edition = "2018"

[dependencies]
assets-rpc-runtime-api = { package = "brml-assets-rpc-runtime-api", path = "./runtime-api" }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"
sp-api = { version = "2.0.0-dev", git = "https://github.com/paritytech/substrate" }
sp-runtime = { version = "2.0.0-dev", git = "https://github.com/paritytech/substrate.git" }
sp-blockchain = { version = "2.0.0-dev", git = "https://github.com/paritytech/substrate.git" }
