[package]
name = "subkey"
version = "0.8.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "subkey"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
futures = "0.1.29"
hex = "0.4.2"
jsonrpc-core-client = { version = "15.1", features = ["http"] }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
structopt = "0.3.14"
tokio = "0.1.22"

[features]
bench = []
