[package]
name = "bifrost-oracle"
version = "0.8.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"

[dependencies]
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
chainlink = { package = "pallet-chainlink", path = "../chainlink", default-features = false }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
node-primitives = { path = "../../node/primitives", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"sp-std/std",
	"chainlink/std",
	"node-primitives/std",
	"sp-runtime/std",
]
