[package]
name = "bifrost-swap"
version = "0.8.0"
authors = ["Liebi Technologies <bifrost@liebi.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
fixed-point = { package = "substrate-fixed", git = "https://github.com/encointer/substrate-fixed", default-features = false }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
node-primitives = { path = "../../node/primitives", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
orml-traits = { version = "0.4.1-dev", default-features = false }

[dev-dependencies]
orml-tokens = { version = "0.4.1-dev", default-features = false}
orml-currencies = { version = "0.4.1-dev", default-features = false }
float-cmp = "0.8.0"
sp-core = "3.0.0"
sp-io = "3.0.0"
pallet-balances = { version = "3.0.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"node-primitives/std",
	"sp-runtime/std",
	"orml-traits/std",
	"orml-currencies/std",
	"orml-tokens/std"
]
