[package]
name = "brml-settlement"
version = "0.1.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sr-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false }
system = { package = "frame-system", git = "https://github.com/paritytech/substrate", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate", default-features = false }
node-primitives = { path = "../../node/primitives", default-features = false }
brml-assets = { path = "../assets", default-features = false }

[dev-dependencies]
substrate-primitives = { git = "https://github.com/paritytech/substrate" }
runtime-io = { package = "sr-io", git = "https://github.com/paritytech/substrate" }

[features]
default = ["std"]
std = [
	"codec/std",
	"sr-primitives/std",
	"frame-support/std",
	"system/std",
	"rstd/std",
    "node-primitives/std",
	"brml-assets/std",
]
