[package]
name = "bifrost-salp-lite-rpc-runtime-api"
version = "0.8.0"
authors = ["Ron Yang<yrong1997@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10", default-features = false }
node-primitives = { path = "../../../../node/primitives", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"node-primitives/std",
]
