[package]
name = "brml-exchange-rpc"
version = "0.2.3"
authors = ["Jamie Deng <djptux@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.1", default-features = false, features = ["derive"] }
exchange-rpc-runtime-api = { package = "brml-exchange-rpc-runtime-api", path = "./runtime-api" }
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"
sp-api = { version = "2.0.0-alpha.4", git = "https://github.com/paritytech/substrate" }
sp-runtime = { version = "2.0.0-alpha.4", git = "https://github.com/paritytech/substrate.git" }
sp-blockchain = { version = "2.0.0-alpha.4", git = "https://github.com/paritytech/substrate.git" }
