[package]
name = "brml-convert-rpc"
version = "0.4.5"
authors = ["Jamie Deng <djptux@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
convert-rpc-runtime-api = { package = "brml-convert-rpc-runtime-api", path = "./runtime-api" }
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"
sp-api = "2.0.0-rc6"
sp-runtime = "2.0.0-rc6"
sp-blockchain = "2.0.0-rc6"
