[package]
name = "brml-convert-rpc"
version = "0.6.0"
authors = ["Jamie Deng <djptux@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.6", default-features = false, features = ["derive"] }
convert-rpc-runtime-api = { package = "brml-convert-rpc-runtime-api", path = "./runtime-api" }
jsonrpc-core = "15.1.0"
jsonrpc-core-client = "15.1.0"
jsonrpc-derive = "15.1.0"
sp-api = "2.0.0"
sp-runtime = "2.0.0"
sp-blockchain = "2.0.0"
