[package]
name = "brml-assets-rpc-runtime-api"
version = "0.2.3"
authors = ["Jamie Deng <djptux@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-api = { version = "2.0.0-alpha.4", git = "https://github.com/paritytech/substrate", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
]
